FROM rust:1-bookworm as builder

WORKDIR /code
COPY . .

# Build with kafka feature explicitly enabled
RUN cargo build --release --features kafka

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /code/target/release/oura /usr/local/bin/oura

ENTRYPOINT [ "oura" ]